name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        example: [NVF2-Can/examples/main_tx.cpp, NVF2-Can/examples/main_rx.cpp, NVF2-Can/examples/main_tx_analog.cpp, NVF2-Can/examples/main_passthru.cpp]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Run PlatformIO
        run: pio ci --lib="." --lib="NVF2-Can/*" --lib="NVF2-Can/examples/board_dfs.h" --board=uno
        # run: pio ci --lib="." --lib="NVF2-Can/*" --lib="NVF2-Can/examples/board_dfs.h" --board=bluepill_f103c8
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
          PLATFORMIO_BUILD_FLAGS: -D BOARD_UNO